import type { ChapterData } from '../../../data/chapters'
import { knowledgePoints } from './knowledgePoints'

const baseChapters: ChapterData[] = [
  {
    id: 'ch1',
    title: '代数基础',
    subtitle: '实数、整式与根式',
    description: '实数概念、整式运算、分式方程、二次根式。',
    order: 1,
    knowledgePointIds: [],
    questionCount: 31,
    difficulty: 'medium',
    estimatedTime: 480,
    color: '#5B7CF9',
    icon: '🔢',
    isKeyChapter: true,
    sections: ['实数概念', '整式运算', '分式方程', '二次根式'],
  },
  {
    id: 'ch2',
    title: '方程与不等式',
    subtitle: '一次方程、方程组与不等式',
    description: '一元一次方程、二元一次方程组、不等式与不等式组。',
    order: 2,
    knowledgePointIds: [],
    questionCount: 26,
    difficulty: 'medium',
    estimatedTime: 420,
    color: '#10B981',
    icon: '✍️',
    isKeyChapter: true,
    sections: ['一元一次方程', '二元一次方程组', '不等式', '不等式组'],
  },
  {
    id: 'ch3',
    title: '函数初步',
    subtitle: '函数与图像基础',
    description: '函数概念、一次函数、反比例函数、二次函数初步。',
    order: 3,
    knowledgePointIds: [],
    questionCount: 32,
    difficulty: 'hard',
    estimatedTime: 360,
    color: '#F59E0B',
    icon: '📈',
    isKeyChapter: true,
    sections: ['函数概念', '一次函数', '反比例函数', '二次函数初步'],
  },
  {
    id: 'ch4',
    title: '三角形与全等',
    subtitle: '基础几何证明',
    description: '三角形概念、全等三角形、等腰三角形、直角三角形。',
    order: 4,
    knowledgePointIds: [],
    questionCount: 32,
    difficulty: 'medium',
    estimatedTime: 300,
    color: '#8B5CF6',
    icon: '📐',
    isKeyChapter: false,
    sections: ['三角形概念', '全等三角形', '等腰三角形', '直角三角形'],
  },
  {
    id: 'ch5',
    title: '四边形',
    subtitle: '平行四边形到梯形',
    description: '平行四边形、矩形菱形正方形、梯形。',
    order: 5,
    knowledgePointIds: [],
    questionCount: 24,
    difficulty: 'medium',
    estimatedTime: 240,
    color: '#EC4899',
    icon: '⬜',
    isKeyChapter: false,
    sections: ['平行四边形', '矩形', '菱形', '正方形', '梯形'],
  },
  {
    id: 'ch6',
    title: '相似形',
    subtitle: '比例线段与位似',
    description: '相似形概念、相似三角形、位似变换、比例线段。',
    order: 6,
    knowledgePointIds: [],
    questionCount: 32,
    difficulty: 'hard',
    estimatedTime: 180,
    color: '#06B6D4',
    icon: '📏',
    isKeyChapter: true,
    sections: ['相似形概念', '相似三角形', '位似变换', '比例线段'],
  },
  {
    id: 'ch7',
    title: '概率统计',
    subtitle: '统计图表与概率初步',
    description: '数据收集与整理、统计图表、频数分布、数据特征分析、概率初步。',
    order: 7,
    knowledgePointIds: [],
    questionCount: 72,
    difficulty: 'easy',
    estimatedTime: 480,
    color: '#84CC16',
    icon: '📊',
    isKeyChapter: false,
    sections: ['数据整理', '统计图表', '频数分布', '数据特征', '概率初步'],
  },
  {
    id: 'ch8',
    title: '综合应用',
    subtitle: '代数几何综合与实际问题',
    description: '代数几何综合、实际应用问题、最值问题。',
    order: 8,
    knowledgePointIds: [],
    questionCount: 24,
    difficulty: 'hard',
    estimatedTime: 300,
    color: '#F97316',
    icon: '🧩',
    isKeyChapter: true,
    sections: ['代数几何综合', '实际应用问题', '最值问题'],
  },
]

export const chapters: ChapterData[] = baseChapters.map((chapter) => ({
  ...chapter,
  knowledgePointIds: knowledgePoints
    .filter(
      (knowledgePoint) =>
        knowledgePoint.chapterId === chapter.id && !knowledgePoint.id.endsWith('_example')
    )
    .map((knowledgePoint) => knowledgePoint.id),
}))
