import type { ChapterData } from '../../../data/chapters'
import { knowledgePoints } from './knowledgePoints'

const baseChapters: ChapterData[] = [
  {
    id: 'ch1',
    title: '二次函数',
    subtitle: '图像、解析式与最值主干',
    description: '初三函数主干专题，围绕图像特征、解析式求法、最值问题和综合应用展开冲刺训练。',
    order: 1,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'hard',
    estimatedTime: 180,
    color: '#7C3AED',
    icon: '📈',
    isKeyChapter: true,
    sections: ['图像与性质', '解析式求法', '最值与综合'],
  },
  {
    id: 'ch2',
    title: '一元二次方程',
    subtitle: '解法、判别式与应用主干',
    description: '初三代数主干专题，围绕解法、判别式、根的关系和实际建模展开系统训练。',
    order: 2,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'medium',
    estimatedTime: 150,
    color: '#2563EB',
    icon: '✍️',
    isKeyChapter: true,
    sections: ['基本概念与解法', '判别式与根系关系', '实际应用'],
  },
  {
    id: 'ch3',
    title: '圆',
    subtitle: '性质、切线与圆综合主干',
    description: '初三几何主干专题，聚焦圆的性质、切线判定、位置关系和圆综合的常见入口。',
    order: 3,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'hard',
    estimatedTime: 210,
    color: '#F59E0B',
    icon: '⭕',
    isKeyChapter: true,
    sections: ['圆的基本性质', '切线与位置关系', '圆综合'],
  },
  {
    id: 'ch4',
    title: '相似与锐角三角函数',
    subtitle: '相似、函数值与解直角三角形',
    description: '初三几何桥梁专题，连接比例线段、相似证明、锐角三角函数和实际应用建模。',
    order: 4,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'hard',
    estimatedTime: 210,
    color: '#10B981',
    icon: '📐',
    isKeyChapter: true,
    sections: ['比例线段与相似判定', '相似性质与应用', '锐角三角函数与解直角三角形'],
  },
  {
    id: 'ch5',
    title: '反比例函数与函数综合',
    subtitle: '图像、面积与函数联动',
    description: '初三函数拓展专题，围绕反比例函数的图像、参数、面积定值和函数综合展开训练。',
    order: 5,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'hard',
    estimatedTime: 180,
    color: '#EF4444',
    icon: '📊',
    isKeyChapter: true,
    sections: ['图像与性质', '参数与面积', '函数综合'],
  },
  {
    id: 'ch6',
    title: '统计与概率',
    subtitle: '统计量、图表分析与古典概率',
    description: '初三稳分专题，围绕统计量、图表阅读、古典概率和综合建模承接中考基础分与中档分。',
    order: 6,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'medium',
    estimatedTime: 150,
    color: '#14B8A6',
    icon: '🎲',
    isKeyChapter: true,
    sections: ['统计量与波动', '图表分析与数据理解', '概率模型与求法'],
  },
  {
    id: 'ch7',
    title: '几何综合',
    subtitle: '辅助线、圆相似与存在性',
    description: '初三几何综合入门专题，围绕辅助线策略、圆相似联动、最值计算和存在性分类展开。',
    order: 7,
    knowledgePointIds: [],
    questionCount: 12,
    difficulty: 'hard',
    estimatedTime: 210,
    color: '#F97316',
    icon: '🧩',
    isKeyChapter: true,
    sections: ['辅助线与图形联动', '圆相似与四边形综合', '计算最值与存在性'],
  },
  {
    id: 'ch8',
    title: '代数综合与中考压轴入门',
    subtitle: '函数方程、参数分类与压轴拆题',
    description: '初三压轴入门专题，围绕函数方程联动、参数问题、分类讨论、最值范围和拆题方法展开。',
    order: 8,
    knowledgePointIds: [],
    questionCount: 10,
    difficulty: 'hard',
    estimatedTime: 210,
    color: '#6366F1',
    icon: '🧠',
    isKeyChapter: true,
    sections: ['函数方程联动', '参数与分类讨论', '最值范围与压轴拆解'],
  },
]

export const chapters: ChapterData[] = baseChapters.map((chapter) => ({
  ...chapter,
  knowledgePointIds: knowledgePoints
    .filter((knowledgePoint) => knowledgePoint.chapterId === chapter.id)
    .map((knowledgePoint) => knowledgePoint.id),
}))

export const getChapterById = (id: string): ChapterData | undefined => {
  return chapters.find((chapter) => chapter.id === id)
}
