import type { QuestionData } from '../../../data/questions'

export const questions: QuestionData[] = [
  {
    id: 'g9_q_001',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_001',
    type: 'fill_blank',
    content: '抛物线 y = x² - 6x + 8 的对称轴是____。',
    answer: 'x=3',
    analysis: '对称轴公式是 x=-b/2a，所以 x=6/2=3。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '先识别 a、b，再直接套对称轴公式。',
    steps: [
      {
        step: 1,
        title: '识别系数',
        content: '把二次函数写成 y=ax²+bx+c 的标准形式，可得 a=1，b=-6。',
      },
      {
        step: 2,
        title: '套用对称轴公式',
        content: '对称轴公式为 x=-b/2a，所以 x=-(-6)/(2×1)=3。',
        highlight: true,
      },
    ],
    keyPoints: ['二次函数对称轴公式', '图像与性质'],
    commonMistakes: ['把 b 的符号看错', '把 2a 漏写成 a'],
  },
  {
    id: 'g9_q_002',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_003',
    type: 'single_choice',
    content: '函数 y = -x² + 2x + 3 的最大值为（ ）',
    options: ['A. 3', 'B. 4', 'C. -4', 'D. 1'],
    answer: 'B',
    analysis: '对称轴 x=1，代入得 y=4，且抛物线开口向下，所以最大值是 4。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '开口向下先想最大值，最大值看顶点。',
    steps: [
      {
        step: 1,
        title: '判断最值类型',
        content: '二次项系数 a=-1<0，所以抛物线开口向下，顶点对应最大值。',
      },
      {
        step: 2,
        title: '求对称轴',
        content: '由 x=-b/2a，可得 x=-2/(2×-1)=1。',
      },
      {
        step: 3,
        title: '求顶点纵坐标',
        content: '把 x=1 代入函数，得 y=-(1)²+2×1+3=4，所以最大值为 4。',
        highlight: true,
      },
    ],
    keyPoints: ['开口方向判断最值', '顶点坐标', '对称轴公式'],
    commonMistakes: ['看到最值就直接代常数项', '忘记先判断开口方向'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_003',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_002',
    type: 'judge',
    content: '已知抛物线与 x 轴交于两点，则解析式一定能写成 y=a(x-x1)(x-x2)。',
    answer: '正确',
    analysis: '只要已知两个实数零点，就可以写成交点式。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'basic',
    thinking: '交点式的核心前提是先知道两个实数零点。',
    steps: [
      {
        step: 1,
        title: '识别已知条件',
        content: '题目说抛物线与 x 轴交于两点，也就是知道了两个实数零点。',
      },
      {
        step: 2,
        title: '套用交点式',
        content: '已知两个零点 x₁、x₂ 时，解析式可写成 y=a(x-x₁)(x-x₂)。',
        highlight: true,
      },
    ],
    keyPoints: ['交点式', '零点与交点'],
    commonMistakes: ['只有一个交点时也机械写成交点式', '忘记前面还要有系数 a'],
  },
  {
    id: 'g9_q_010',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_010',
    type: 'single_choice',
    content: '函数 y = x² - 2x - 3 与 x 轴交点的个数是（ ）',
    options: ['A. 0 个', 'B. 1 个', 'C. 2 个', 'D. 无法确定'],
    answer: 'C',
    analysis: '方程 x²-2x-3=0 可化为 (x-3)(x+1)=0，有两个不相等实数根，所以有 2 个交点。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '交点个数问题先转成方程根的个数问题。',
    steps: [
      {
        step: 1,
        title: '转化为方程',
        content: '与 x 轴交点满足 y=0，所以先解 x²-2x-3=0。',
      },
      {
        step: 2,
        title: '求根',
        content: '方程分解为 (x-3)(x+1)=0，可得两个不相等实数根 x=3 和 x=-1。',
        highlight: true,
      },
      {
        step: 3,
        title: '回到图像',
        content: '两个不相等实数根对应图像与 x 轴有两个交点。',
      },
    ],
    keyPoints: ['函数与方程联系', '交点个数与根的个数'],
    commonMistakes: ['只判断了能否分解，没有回到交点个数', '把与 y 轴交点和与 x 轴交点混淆'],
  },
  {
    id: 'g9_q_011',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_011',
    type: 'judge',
    content: '解决二次函数面积题时，通常要先把面积写成关于某个变量的函数式。',
    answer: '正确',
    analysis: '只有先把面积表示出来，后面才能继续做最值或存在性分析。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '面积综合题最怕一上来只盯图形，先把面积写成含变量的式子，后面最值和存在性才有抓手。',
    steps: [
      {
        step: 1,
        title: '先确定变量',
        content: '面积题中通常要先找一个会变化的点或长度，把它设成变量。',
      },
      {
        step: 2,
        title: '把面积写成代数式',
        content: '根据面积公式，把底和高或相关线段都表示成关于该变量的式子。',
        highlight: true,
      },
      {
        step: 3,
        title: '再研究后续问题',
        content: '只有得到面积函数，才能继续分析最值、取值范围或是否存在。',
      },
    ],
    keyPoints: ['面积建模', '变量意识', '函数思想'],
    commonMistakes: ['只画图不列式', '把面积题当成纯几何证明题处理'],
  },
  {
    id: 'g9_q_016',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_003',
    type: 'fill_blank',
    content: '函数 y = (x-2)² + 7 的最小值是____。',
    answer: '7',
    analysis: '抛物线开口向上，顶点纵坐标就是最小值，所以最小值为 7。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '顶点式里，顶点纵坐标常直接给出最值。',
    steps: [
      {
        step: 1,
        title: '判断开口方向',
        content: '二次项系数为正，抛物线开口向上。',
      },
      {
        step: 2,
        title: '读取顶点纵坐标',
        content: '函数 y=(x-2)²+7 的顶点纵坐标是 7，所以最小值为 7。',
        highlight: true,
      },
    ],
    keyPoints: ['顶点式', '最值'],
    commonMistakes: ['看到平方项就忘记常数项 7', '把最小值和顶点横坐标混淆'],
  },
  {
    id: 'g9_q_017',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_010',
    type: 'judge',
    content: '二次函数与 x 轴交点的横坐标，就是对应一元二次方程的实数根。',
    answer: '正确',
    analysis: '令 y=0 得到方程，解出来的 x 就是交点横坐标。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '函数图像和方程根之间最直接的桥梁就是“令 y=0”。',
    steps: [
      {
        step: 1,
        title: '写出交点条件',
        content: '与 x 轴交点一定满足 y=0。',
      },
      {
        step: 2,
        title: '转化为方程根',
        content: '因此解二次方程得到的实数根，就是交点横坐标。',
        highlight: true,
      },
    ],
    keyPoints: ['函数与方程联系', '交点横坐标'],
    commonMistakes: ['把交点横坐标误看成纵坐标', '忘记与 x 轴对应 y=0'],
  },
  {
    id: 'g9_q_018',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_002',
    type: 'fill_blank',
    content: '已知抛物线顶点为 (0, -3)，且经过点 (1, -2)，则其解析式可写为____。',
    answer: 'y=x²-3',
    analysis: '设 y=ax²-3，代入 (1,-2) 得 a=1，所以解析式为 y=x²-3。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '顶点在 y 轴上，说明对称轴就是 x=0，优先考虑顶点式的简化版本。',
    steps: [
      {
        step: 1,
        title: '根据顶点设式',
        content: '顶点为 (0,-3)，可设解析式为 y=ax²-3。',
        highlight: true,
      },
      {
        step: 2,
        title: '代入已知点',
        content: '把点 (1,-2) 代入得 -2=a×1²-3，所以 a=1。',
      },
      {
        step: 3,
        title: '写出解析式',
        content: '把 a=1 代回，可得 y=x²-3。',
      },
    ],
    keyPoints: ['顶点式', '待定系数法', '特殊顶点位置'],
    commonMistakes: ['顶点在 y 轴上却还写成三参数一般式', '忘记顶点纵坐标直接就是常数项'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_033',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_011',
    type: 'single_choice',
    content: '在平面直角坐标系中，点 P 在抛物线 y=x²-4x+3 上运动。若以点 P、点 O 和点 A(4,0) 为顶点的三角形面积为 S，则 S 的最小值为（ ）',
    options: ['A. 1', 'B. 2', 'C. 3', 'D. 4'],
    answer: 'B',
    analysis: '点 P 的纵坐标为 y=x²-4x+3=(x-2)²-1。三角形 OAP 的底 OA 长为 4，高为 |y|，所以 S=2|y|。当抛物线顶点处 y=-1 时，|y| 最小为 1，因此 S 最小为 2。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '这类北京风格函数综合题，通常先把面积转成纵坐标绝对值，再用顶点控制最值。',
    steps: [
      {
        step: 1,
        title: '把面积转成函数',
        content: '底边 OA 在 x 轴上，长度固定为 4，所以三角形面积 S = 1/2 × 4 × |y| = 2|y|。',
      },
      {
        step: 2,
        title: '分析 y 的最值',
        content: '抛物线 y=x²-4x+3 可化为 y=(x-2)²-1，顶点纵坐标为 -1。',
        highlight: true,
      },
      {
        step: 3,
        title: '求面积最小值',
        content: '|y| 的最小值为 1，所以 S 的最小值为 2。',
      },
    ],
    keyPoints: ['二次函数最值', '面积建模', '绝对值处理'],
    commonMistakes: ['把高直接写成 y 而忘记绝对值', '求出顶点后没有回到面积表达式'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_034',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_010',
    type: 'judge',
    content: '若抛物线 y=ax²+bx+c 与 x 轴有两个不同交点，则对应方程 ax²+bx+c=0 的判别式一定大于 0。',
    answer: '正确',
    analysis: '与 x 轴有两个不同交点，说明方程有两个不相等实数根，因此判别式大于 0。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '图像语言和方程语言要互相翻译：两个不同交点，对应两个不等实根。',
    steps: [
      {
        step: 1,
        title: '读懂图像条件',
        content: '抛物线与 x 轴有两个不同交点，说明当 y=0 时方程有两个不同的实数解。',
      },
      {
        step: 2,
        title: '翻译成方程结论',
        content: '二次方程有两个不同实数根时，判别式必须满足 Δ>0。',
        highlight: true,
      },
      {
        step: 3,
        title: '判断命题真伪',
        content: '因此题目中的说法正确。',
      },
    ],
    keyPoints: ['函数与方程联系', '判别式', '交点与根'],
    commonMistakes: ['只记住“有交点”，没区分一个还是两个', '把 Δ>0 和 Δ≥0 混淆'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_004',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_004',
    type: 'fill_blank',
    content: '方程 x² - 9 = 0 的两个实数根是____。',
    answer: 'x=3 或 x=-3',
    analysis: '因式分解得 (x-3)(x+3)=0，所以 x=3 或 x=-3。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '平方差结构先考虑因式分解。',
    steps: [
      {
        step: 1,
        title: '因式分解',
        content: 'x²-9=(x-3)(x+3)。',
        highlight: true,
      },
      {
        step: 2,
        title: '利用零积定理',
        content: '令 x-3=0 或 x+3=0，可得 x=3 或 x=-3。',
      },
    ],
    keyPoints: ['因式分解', '平方差公式', '零积定理'],
    commonMistakes: ['只写一个根', '把 x²-9 误分成 (x-9)(x+1)'],
  },
  {
    id: 'g9_q_005',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_005',
    type: 'single_choice',
    content: '方程 x² + 2x + 5 = 0 的根的情况是（ ）',
    options: ['A. 两个不相等实数根', 'B. 两个相等实数根', 'C. 没有实数根', 'D. 无法判断'],
    answer: 'C',
    analysis: '判别式 Δ=2²-4×1×5=4-20=-16<0，所以没有实数根。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '题目问根的情况时，不一定要求根，优先考虑判别式。',
    steps: [
      {
        step: 1,
        title: '确定 a、b、c',
        content: '由方程 x²+2x+5=0 可得 a=1，b=2，c=5。',
      },
      {
        step: 2,
        title: '计算判别式',
        content: 'Δ=b²-4ac=2²-4×1×5=4-20=-16。',
        highlight: true,
      },
      {
        step: 3,
        title: '判断根的情况',
        content: '因为 Δ<0，所以方程没有实数根。',
      },
    ],
    keyPoints: ['判别式', '根的情况判断'],
    commonMistakes: ['把判别式算成 20-4', '算出 Δ 后忘记对应结论'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_006',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_006',
    type: 'judge',
    content: '一元二次方程应用题求出两个根后，可以直接都作为最终答案。',
    answer: '错误',
    analysis: '应用题必须结合实际情境验根，可能有不符合实际的根。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '应用题求出的根只是“数学结果”，还要回到题意里检查是否合理。',
    steps: [
      {
        step: 1,
        title: '先得到方程的根',
        content: '一元二次方程通常可能有两个实数根。',
      },
      {
        step: 2,
        title: '结合实际验根',
        content: '应用题中的长度、时间、数量等要满足实际意义，不符合条件的根要舍去。',
        highlight: true,
      },
    ],
    keyPoints: ['验根', '应用题'],
    commonMistakes: ['求完两个根就都写答案', '不检查负数或不合理数值'],
  },
  {
    id: 'g9_q_012',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_012',
    type: 'fill_blank',
    content: '把 x² + 8x + 3 配方后可写成____。',
    answer: '(x+4)²-13',
    analysis: 'x²+8x+3 = x²+8x+16-13 = (x+4)²-13。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '配方法本质是凑完全平方，关键看一次项系数的一半。',
    steps: [
      {
        step: 1,
        title: '看一次项系数',
        content: '一次项系数是 8，它的一半是 4。',
      },
      {
        step: 2,
        title: '凑完全平方',
        content: 'x²+8x+3 = x²+8x+16-13。',
      },
      {
        step: 3,
        title: '整理为平方形式',
        content: '所以原式 = (x+4)²-13。',
        highlight: true,
      },
    ],
    keyPoints: ['配方法', '完全平方公式'],
    commonMistakes: ['只加不减', '把 8 的一半写错成 8'],
  },
  {
    id: 'g9_q_013',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_013',
    type: 'single_choice',
    content: '若抛物线 y = x² - 6x + 9 与 x 轴只有一个交点，则方程 x² - 6x + 9 = 0（ ）',
    options: ['A. 有两个不等实数根', 'B. 有两个相等实数根', 'C. 没有实数根', 'D. 无法判断'],
    answer: 'B',
    analysis: '与 x 轴只有一个交点，对应两个相等的实数根。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '“只有一个交点”不是“只有一个根”，而是两个根重合，对应相等实根。',
    steps: [
      {
        step: 1,
        title: '翻译图像信息',
        content: '抛物线与 x 轴只有一个交点，说明二次函数图像在 x 轴上与之相切。',
      },
      {
        step: 2,
        title: '转成方程语言',
        content: '这对应方程有两个相等的实数根。',
        highlight: true,
      },
      {
        step: 3,
        title: '匹配选项',
        content: '因此应选“有两个相等实数根”。',
      },
    ],
    keyPoints: ['函数与方程联系', '相等实根', '图像判根'],
    commonMistakes: ['把“一个交点”理解成“一个实数根”', '忘记重根本质上是两个相等实根'],
  },
  {
    id: 'g9_q_019',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_012',
    type: 'judge',
    content: '配方法只能用于解方程，不能用于研究函数最值。',
    answer: '错误',
    analysis: '配方法既能解方程，也能把二次函数化为顶点式来研究最值。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'basic',
    thinking: '配方法不只是解方程工具，它也是函数变形工具。',
    steps: [
      {
        step: 1,
        title: '看配方法的本质',
        content: '配方法是把代数式凑成完全平方形式。',
      },
      {
        step: 2,
        title: '联系函数应用',
        content: '二次函数配方后能化成顶点式，因此也可以用来研究最值。',
        highlight: true,
      },
    ],
    keyPoints: ['配方法', '顶点式', '最值'],
    commonMistakes: ['把配方法只局限在解方程', '不会把式子变形和函数联系起来'],
  },
  {
    id: 'g9_q_020',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_005',
    type: 'fill_blank',
    content: '若方程 x² + mx + 4 = 0 有两个相等实数根，则 m = ____。',
    answer: '±4',
    analysis: '由判别式 m²-16=0，得 m=±4。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '“两个相等实数根”对应判别式等于 0，这是参数题的固定入口。',
    steps: [
      {
        step: 1,
        title: '写出判别式条件',
        content: '两个相等实数根说明 Δ=0。',
        highlight: true,
      },
      {
        step: 2,
        title: '代入系数',
        content: '对方程 x²+mx+4=0，有 Δ=m²-4×1×4=m²-16。',
      },
      {
        step: 3,
        title: '解参数方程',
        content: '令 m²-16=0，得 m=±4。',
      },
    ],
    keyPoints: ['参数题', '判别式等于零'],
    commonMistakes: ['忘记“相等实根”是 Δ=0 不是 Δ>0', '最后只写一个 m 值'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_021',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_006',
    type: 'single_choice',
    content: '矩形面积为 35，长比宽多 2。若设宽为 x，则列出的方程应为（ ）',
    options: ['A. x(x-2)=35', 'B. x(x+2)=35', 'C. 2x=35', 'D. x²+2=35'],
    answer: 'B',
    analysis: '宽为 x，长为 x+2，面积关系是 x(x+2)=35。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '应用题先找量之间的关系，再判断哪个式子最符合题意。',
    steps: [
      {
        step: 1,
        title: '设未知数',
        content: '设宽为 x，则长为 x+2。',
      },
      {
        step: 2,
        title: '根据面积列式',
        content: '矩形面积 = 长 × 宽，所以列式为 x(x+2)=35。',
        highlight: true,
      },
    ],
    keyPoints: ['应用建模', '面积关系'],
    commonMistakes: ['把“长比宽多 2”写成 x-2', '面积关系写成加法'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_035',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_005',
    type: 'single_choice',
    content: '关于 x 的方程 x²-(m+1)x+m=0 有两个相等的实数根，则 m 的值为（ ）',
    options: ['A. 0', 'B. 1', 'C. -1', 'D. 4'],
    answer: 'B',
    analysis: '判别式为 (m+1)²-4m = m²-2m+1 = (m-1)²。要有两个相等实数根，则判别式等于 0，所以 m=1。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格参数题常先把判别式化简成完全平方，再快速判断参数。',
    steps: [
      {
        step: 1,
        title: '写出判别式',
        content: 'Δ = [-(m+1)]² - 4×1×m = (m+1)² - 4m。',
      },
      {
        step: 2,
        title: '化简判别式',
        content: 'Δ = m²+2m+1-4m = m²-2m+1 = (m-1)²。',
        highlight: true,
      },
      {
        step: 3,
        title: '利用相等实根条件',
        content: '因为要有两个相等实数根，所以 Δ=0，得 (m-1)²=0，因此 m=1。',
      },
    ],
    keyPoints: ['判别式', '参数题', '完全平方'],
    commonMistakes: ['符号处理出错', '忘记相等实根对应 Δ=0'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_036',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_006',
    type: 'fill_blank',
    content: '某商品经过两次连续降价后，价格由 200 元变为 162 元。若每次降价的百分率相同，设每次降价的百分率为 x，则列出的方程为____。',
    answer: '200(1-x)²=162',
    analysis: '两次连续按同一百分率降价，第一次后价格为 200(1-x)，第二次后为 200(1-x)²，所以方程为 200(1-x)²=162。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '增长率、降价率类题先写“变化后 = 变化前 × (1±率)”的模型。',
    steps: [
      {
        step: 1,
        title: '写出第一次降价后的价格',
        content: '原价是 200 元，第一次降价后价格为 200(1-x)。',
      },
      {
        step: 2,
        title: '写出第二次降价后的价格',
        content: '第二次仍按同样百分率降价，所以价格变为 200(1-x)(1-x)=200(1-x)²。',
        highlight: true,
      },
      {
        step: 3,
        title: '与现价对应',
        content: '已知最终价格为 162 元，因此列方程 200(1-x)²=162。',
      },
    ],
    keyPoints: ['百分率模型', '连续变化', '应用建模'],
    commonMistakes: ['两次降价写成 200(1-2x)', '只写出第一次降价后的价格'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_007',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_007',
    type: 'fill_blank',
    content: '若同弧所对圆心角为 100°，则所对圆周角为____。',
    answer: '50°',
    analysis: '同弧所对圆周角等于圆心角的一半。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '圆周角问题先找“同弧”，再套一半关系。',
    steps: [
      {
        step: 1,
        title: '确认对应同一条弧',
        content: '题目给的是同弧所对的圆心角和圆周角。',
      },
      {
        step: 2,
        title: '套用一半关系',
        content: '圆周角等于同弧所对圆心角的一半，所以是 50°。',
        highlight: true,
      },
    ],
    keyPoints: ['圆周角定理', '同弧'],
    commonMistakes: ['把圆周角和圆心角看成相等', '没注意“同弧”条件'],
  },
  {
    id: 'g9_q_008',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_008',
    type: 'single_choice',
    content: '若圆心到一条直线的距离等于半径，则这条直线与圆（ ）',
    options: ['A. 相离', 'B. 相切', 'C. 相交', 'D. 不能确定'],
    answer: 'B',
    analysis: '距离等于半径对应相切。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '直线与圆的位置关系，优先比较圆心到直线的距离 d 和半径 r。',
    steps: [
      {
        step: 1,
        title: '回忆判定标准',
        content: '若 d>r，相离；d=r，相切；d<r，相交。',
      },
      {
        step: 2,
        title: '代入条件判断',
        content: '题目给出 d=r，所以直线与圆相切。',
        highlight: true,
      },
    ],
    keyPoints: ['位置关系', 'd 与 r 的比较'],
    commonMistakes: ['把相切和相交混淆', '忘记比较的是圆心到直线的距离'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_009',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_009',
    type: 'judge',
    content: '圆内接四边形的对角互补。',
    answer: '正确',
    analysis: '这是圆内接四边形的核心性质。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'basic',
    thinking: '圆内接四边形最重要的一条性质就是“对角互补”。',
    steps: [
      {
        step: 1,
        title: '识别图形',
        content: '题目研究的是圆内接四边形。',
      },
      {
        step: 2,
        title: '回忆核心性质',
        content: '圆内接四边形的对角互补，所以题目说法正确。',
        highlight: true,
      },
    ],
    keyPoints: ['圆内接四边形', '对角互补'],
    commonMistakes: ['只记边或角的一般性质，忘记对角互补这条主性质'],
  },
  {
    id: 'g9_q_014',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_014',
    type: 'judge',
    content: '在同圆中，若两条弦相等，则它们所对的弧也相等。',
    answer: '正确',
    analysis: '这是同圆中的弧弦基本关系。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '在同圆里，等弦、等弧、等圆心角之间可以互相对应。',
    steps: [
      {
        step: 1,
        title: '抓住前提',
        content: '题目强调“同圆中”。',
      },
      {
        step: 2,
        title: '应用弧弦关系',
        content: '同圆中等弦对等弧，所以说法正确。',
        highlight: true,
      },
    ],
    keyPoints: ['弧弦关系', '同圆前提'],
    commonMistakes: ['忽略同圆前提', '只会由等弧推等弦，不会反向使用'],
  },
  {
    id: 'g9_q_015',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_015',
    type: 'fill_blank',
    content: '圆内接四边形中，若一个内角为 68°，则它的对角为____。',
    answer: '112°',
    analysis: '圆内接四边形对角互补，所以 180°-68°=112°。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '求圆内接四边形的对角，先用互补关系。',
    steps: [
      {
        step: 1,
        title: '写出对角互补',
        content: '圆内接四边形的对角和为 180°。',
      },
      {
        step: 2,
        title: '直接计算',
        content: '所以对角为 180°-68°=112°。',
        highlight: true,
      },
    ],
    keyPoints: ['圆内接四边形', '对角互补'],
    commonMistakes: ['把邻角和对角混淆', '计算时忘记从 180° 中减'],
  },
  {
    id: 'g9_q_022',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_008',
    type: 'judge',
    content: '经过切点的半径一定垂直于切线。',
    answer: '正确',
    analysis: '这是切线的基本性质。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '切线最基础的性质就是“半径到切点，必垂切线”。',
    steps: [
      {
        step: 1,
        title: '确认位置',
        content: '半径连接到切点，这是切线性质常见的标准图形。',
      },
      {
        step: 2,
        title: '套用性质',
        content: '经过切点的半径一定垂直于切线，所以说法正确。',
        highlight: true,
      },
    ],
    keyPoints: ['切线性质', '半径与切线垂直'],
    commonMistakes: ['把切线性质和切线判定混淆', '忘记必须经过切点'],
  },
  {
    id: 'g9_q_023',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_014',
    type: 'single_choice',
    content: '在同圆中，若两条弦相等，则它们所对的圆心角（ ）',
    options: ['A. 相等', 'B. 互补', 'C. 互余', 'D. 无法判断'],
    answer: 'A',
    analysis: '同圆中等弦对等弧，对等圆心角。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '题目给的是“等弦”，要立刻联想到弧和圆心角的对应关系。',
    steps: [
      {
        step: 1,
        title: '识别已知条件',
        content: '题目说的是同圆中的两条弦相等。',
      },
      {
        step: 2,
        title: '调用弧弦关系',
        content: '同圆中等弦对等弧，对等圆心角。',
        highlight: true,
      },
      {
        step: 3,
        title: '得到结论',
        content: '因此它们所对的圆心角相等。',
      },
    ],
    keyPoints: ['弧弦关系', '同圆前提'],
    commonMistakes: ['忽略“同圆或等圆”前提', '只记得等弧对等弦，反过来不会用'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_024',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_015',
    type: 'fill_blank',
    content: '同一点引圆的两条切线长若分别为 PA、PB，则有____。',
    answer: 'PA=PB',
    analysis: '由切线长定理，同一点引圆的两条切线长相等。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '看到“同一点引圆的两条切线”，直接联想切线长定理。',
    steps: [
      {
        step: 1,
        title: '识别模型',
        content: 'PA、PB 是从同一点 P 向圆引出的两条切线段。',
      },
      {
        step: 2,
        title: '应用定理',
        content: '根据切线长定理，可得 PA=PB。',
        highlight: true,
      },
    ],
    keyPoints: ['切线长定理'],
    commonMistakes: ['把切线长和半径长度混淆'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_037',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_015',
    type: 'single_choice',
    content: '四边形 ABCD 内接于圆，若 ∠A=80°，则 ∠C 的度数为（ ）',
    options: ['A. 80°', 'B. 90°', 'C. 100°', 'D. 120°'],
    answer: 'C',
    analysis: '圆内接四边形对角互补，所以 ∠C = 180°-80° = 100°。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '看见圆内接四边形和一个角，先想到对角互补。',
    steps: [
      {
        step: 1,
        title: '写出角关系',
        content: '圆内接四边形中，对角互补。',
      },
      {
        step: 2,
        title: '求对角',
        content: '所以 ∠C=180°-80°=100°。',
        highlight: true,
      },
    ],
    keyPoints: ['圆内接四边形', '对角互补'],
    commonMistakes: ['把对角互补错用成相等', '算对角时忘记减法'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_038',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_008',
    type: 'judge',
    content: '若一条直线经过半径的外端并且与该半径垂直，则这条直线是圆的切线。',
    answer: '正确',
    analysis: '这是切线判定定理的直接应用。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '切线判定题常见的标准模板就是“经过半径外端且垂直于半径”。',
    steps: [
      {
        step: 1,
        title: '识别判定条件',
        content: '题目给出一条直线经过半径的外端，并且与该半径垂直。',
      },
      {
        step: 2,
        title: '调用切线判定定理',
        content: '经过半径外端且垂直于半径的直线，就是圆的切线。',
        highlight: true,
      },
      {
        step: 3,
        title: '作出判断',
        content: '因此题目中的说法正确。',
      },
    ],
    keyPoints: ['切线判定定理', '半径与切线垂直', '圆的判定'],
    commonMistakes: ['把切线性质和切线判定混着用', '只记住“垂直”，忘记还要经过半径外端'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_025',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_016',
    type: 'judge',
    content: '若两个三角形有两组对应角分别相等，则这两个三角形一定相似。',
    answer: '正确',
    analysis: '根据两角对应相等判定，两三角形相似。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '相似判定里最稳的是角条件，看到两角相等应优先想到 AA 判定。',
    steps: [
      {
        step: 1,
        title: '识别条件',
        content: '题目给出了两组对应角分别相等。',
      },
      {
        step: 2,
        title: '调用判定方法',
        content: '两角对应相等可以直接判定两个三角形相似。',
        highlight: true,
      },
    ],
    keyPoints: ['相似三角形判定', 'AA 判定'],
    commonMistakes: ['把“全等”与“相似”混淆'],
  },
  {
    id: 'g9_q_026',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_017',
    type: 'fill_blank',
    content: '两个相似三角形的相似比为 2:5，则面积比为____。',
    answer: '4:25',
    analysis: '面积比等于相似比的平方，所以是 4:25。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '遇到面积比，不要直接算面积，先看能否先用相似比平方。',
    steps: [
      {
        step: 1,
        title: '写出相似比',
        content: '已知相似比为 2:5。',
      },
      {
        step: 2,
        title: '转化面积比',
        content: '面积比等于相似比平方，所以面积比为 2²:5²=4:25。',
        highlight: true,
      },
    ],
    keyPoints: ['相似性质', '面积比'],
    commonMistakes: ['把面积比误写成 2:5', '忘记平方'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_027',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_018',
    type: 'single_choice',
    content: '位似图形中，对应点与位似中心的关系是（ ）',
    options: ['A. 互相垂直', 'B. 在同一直线上', 'C. 到位似中心距离相等', 'D. 一定关于中心对称'],
    answer: 'B',
    analysis: '位似图形中，对应点与位似中心始终在同一直线上。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'basic',
    thinking: '位似的核心识别词就是“对应点和位似中心共线”。',
    steps: [
      {
        step: 1,
        title: '识别位似图形特征',
        content: '位似变化保留形状，并且所有对应点都与位似中心相关联。',
      },
      {
        step: 2,
        title: '抓住共线关系',
        content: '对应点与位似中心一定在同一直线上。',
        highlight: true,
      },
    ],
    keyPoints: ['位似', '对应点共线'],
    commonMistakes: ['把位似和中心对称混淆', '忽略“位似中心”这一关键词'],
  },
  {
    id: 'g9_q_028',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_019',
    type: 'fill_blank',
    content: '在直角三角形中，若角 A 为锐角，则 sinA = ____。',
    answer: '对边/斜边',
    analysis: '正弦定义为对边与斜边的比。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '三角函数先固定研究角，再认边。',
    steps: [
      {
        step: 1,
        title: '确定研究角',
        content: '题目研究的是角 A。',
      },
      {
        step: 2,
        title: '回忆定义',
        content: 'sinA 表示角 A 的对边与斜边的比。',
        highlight: true,
      },
    ],
    keyPoints: ['正弦定义', '对边与斜边'],
    commonMistakes: ['把 sin 和 cos 对应关系记混', '未先固定研究角'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_029',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_019',
    type: 'single_choice',
    content: '下列函数值中，tan45° = （ ）',
    options: ['A. √2/2', 'B. 1', 'C. √3/2', 'D. √3'],
    answer: 'B',
    analysis: '45° 的正切值等于 1。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '特殊角函数值要熟记，45° 的正切值是最常考的一个。',
    steps: [
      {
        step: 1,
        title: '识别特殊角',
        content: '45° 属于需要熟记函数值的特殊角。',
      },
      {
        step: 2,
        title: '直接调用结论',
        content: 'tan45°=1，所以选 B。',
        highlight: true,
      },
    ],
    keyPoints: ['特殊角函数值', 'tan45°'],
    commonMistakes: ['把 tan45° 和 sin45° 混淆', '会写符号不会匹配选项'],
  },
  {
    id: 'g9_q_030',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_020',
    type: 'judge',
    content: '解决仰角、俯角应用题时，通常应先画示意图并标清边角关系。',
    answer: '正确',
    analysis: '应用题先画图能避免角和边认错，是解直角三角形的关键步骤。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '仰角俯角题如果不先画图，最容易把对边、邻边和角的位置全弄乱。',
    steps: [
      {
        step: 1,
        title: '先把情境转成图形',
        content: '仰角、俯角应用题本质上都要落成直角三角形示意图。',
      },
      {
        step: 2,
        title: '标清边角关系',
        content: '只有图上把角和边关系标清，后面才能正确使用三角函数，所以题目说法正确。',
        highlight: true,
      },
    ],
    keyPoints: ['仰角俯角', '示意图', '解直角三角形'],
    commonMistakes: ['不画图直接列式', '角和边对应关系标错'],
  },
  {
    id: 'g9_q_031',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_020',
    type: 'single_choice',
    content: '解直角三角形应用题最常用的数学模型是（ ）',
    options: ['A. 一元一次方程', 'B. 直角三角形', 'C. 圆内接四边形', 'D. 平移变换'],
    answer: 'B',
    analysis: '仰角、俯角、测高测距本质都落在直角三角形模型上。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '先别急着选函数，先识别基础图形模型。',
    steps: [
      {
        step: 1,
        title: '识别场景',
        content: '题目说的是解直角三角形应用题。',
      },
      {
        step: 2,
        title: '找底层模型',
        content: '这类题本质是把实际情境转成直角三角形，再用三角函数求解。',
        highlight: true,
      },
    ],
    keyPoints: ['解直角三角形', '应用建模'],
    commonMistakes: ['只记仰角俯角名词，不先建模成直角三角形'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_032',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_017',
    type: 'fill_blank',
    content: '若两个相似三角形的周长比为 3:4，则相似比为____。',
    answer: '3:4',
    analysis: '周长比等于相似比，所以相似比为 3:4。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '相似三角形的周长比和对应边比是同一个比值。',
    steps: [
      {
        step: 1,
        title: '回忆对应关系',
        content: '相似三角形中，周长比等于相似比。',
      },
      {
        step: 2,
        title: '直接得出结论',
        content: '已知周长比是 3:4，所以相似比也是 3:4。',
        highlight: true,
      },
    ],
    keyPoints: ['相似比', '周长比'],
    commonMistakes: ['把周长比误当面积比', '知道结论但不敢直接用'],
  },
  {
    id: 'g9_q_039',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_019',
    type: 'single_choice',
    content: '在 Rt△ABC 中，∠C=90°，若 tanA=3/4，则 sinA 的值为（ ）',
    options: ['A. 3/5', 'B. 4/5', 'C. 5/3', 'D. 4/3'],
    answer: 'A',
    analysis: '由 tanA=3/4，可设对边:邻边=3:4，则斜边为 5，所以 sinA=3/5。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格三角函数题常先由一个比构造直角三角形边长比，再转求其他函数值。',
    steps: [
      {
        step: 1,
        title: '由正切值设边比',
        content: '因为 tanA=3/4，所以可设对边为 3k，邻边为 4k。',
      },
      {
        step: 2,
        title: '求斜边',
        content: '根据勾股定理，斜边为 5k。',
        highlight: true,
      },
      {
        step: 3,
        title: '求正弦值',
        content: 'sinA=对边/斜边=3k/5k=3/5。',
      },
    ],
    keyPoints: ['正切定义', '勾股定理', '特殊构造'],
    commonMistakes: ['把 tanA 和 sinA 直接混用', '边比构造后忘记再求斜边'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_040',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_020',
    type: 'fill_blank',
    content: '某同学在地面上观测旗杆顶端的仰角为 30°，已知该同学到旗杆底端的水平距离为 6 米，则旗杆高度约为____米。',
    answer: '2√3',
    analysis: '设旗杆高度为 h，则 tan30°=h/6。因为 tan30°=√3/3，所以 h=6×√3/3=2√3。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'comprehensive',
    thinking: '仰角题先画直角三角形，水平距离对应邻边，高度对应对边。',
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_041',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_010',
    type: 'single_choice',
    content: '已知抛物线 y=x²-4x+m 与 x 轴交于 A、B 两点，且 AB=2，则 m 的值为（ ）',
    options: ['A. 2', 'B. 3', 'C. 4', 'D. 5'],
    answer: 'B',
    analysis: '交点间距离就是对应方程两个实数根之差的绝对值。对方程 x²-4x+m=0，有 |x₁-x₂|=√Δ=2，所以 Δ=4，即 16-4m=4，解得 m=3。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格函数综合题常把图像信息翻译成方程根的信息，这题的关键就是“AB=2”要转成根差。',
    steps: [
      {
        step: 1,
        title: '把图像条件转成方程条件',
        content: '抛物线与 x 轴交点的横坐标就是方程 x²-4x+m=0 的两个实数根。',
      },
      {
        step: 2,
        title: '利用根差与判别式关系',
        content: '对于二次项系数为 1 的方程，有 |x₁-x₂|=√Δ。题目给出 AB=2，所以 √Δ=2。',
        highlight: true,
      },
      {
        step: 3,
        title: '列方程求参数',
        content: 'Δ=16-4m，令 16-4m=4，解得 m=3。',
      },
    ],
    keyPoints: ['函数与方程联系', '判别式', '交点距离'],
    commonMistakes: ['把 AB=2 直接看成某个交点坐标为 2', '忘记先保证根差来自判别式'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_042',
    chapterId: 'ch1',
    knowledgePointId: 'kp9_002',
    type: 'single_choice',
    content: '抛物线经过点 (1,0)、(3,0)、(0,3)，则它的顶点坐标是（ ）',
    options: ['A. (2, -1)', 'B. (2, 1)', 'C. (1, -3)', 'D. (3, 1)'],
    answer: 'A',
    analysis: '由两个零点 1 和 3，可设解析式为 y=a(x-1)(x-3)。再代入点 (0,3)，得 3a=3，所以 a=1，解析式为 y=x²-4x+3=(x-2)²-1，顶点为 (2,-1)。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '这类综合题先利用零点写交点式，再用额外一点定系数，最后化成顶点式找顶点。',
    steps: [
      {
        step: 1,
        title: '由零点设交点式',
        content: '因为抛物线经过 (1,0)、(3,0)，可设 y=a(x-1)(x-3)。',
      },
      {
        step: 2,
        title: '代入已知点求系数',
        content: '把点 (0,3) 代入，得 3a=3，所以 a=1。',
        highlight: true,
      },
      {
        step: 3,
        title: '化成顶点式',
        content: '解析式为 y=x²-4x+3=(x-2)²-1，因此顶点坐标是 (2,-1)。',
      },
    ],
    keyPoints: ['交点式', '待定系数法', '顶点式'],
    commonMistakes: ['有两个零点还去直接设一般式', '求出解析式后忘记继续求顶点'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_043',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_006',
    type: 'fill_blank',
    content: '某班原计划 8 天完成一批练习册整理任务。实际每天比原计划多整理 12 本，结果提前 2 天完成。原计划每天整理____本。',
    answer: '36',
    analysis: '设原计划每天整理 x 本，则任务总量为 8x。本来提前 2 天，实际用了 6 天，每天整理 x+12 本，所以有 6(x+12)=8x，解得 x=36。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '应用综合题的核心是先抓“总量不变”，再把原计划和实际完成量写成同一个等式。',
    steps: [
      {
        step: 1,
        title: '设未知数',
        content: '设原计划每天整理 x 本。',
      },
      {
        step: 2,
        title: '分别表示总量',
        content: '原计划总量为 8x；实际提前 2 天完成，所以实际共整理 6(x+12) 本。',
      },
      {
        step: 3,
        title: '列方程并求解',
        content: '由总量相同得 6(x+12)=8x，解得 x=36。',
        highlight: true,
      },
    ],
    keyPoints: ['应用建模', '总量不变', '一元二次与一元一次的辨析'],
    commonMistakes: ['提前 2 天却还按 8 天列式', '把“多整理 12 本”误写成总量多 12'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_044',
    chapterId: 'ch2',
    knowledgePointId: 'kp9_005',
    type: 'single_choice',
    content: '关于 x 的方程 x²-(m+1)x+m-2=0 有一个根为 3，则另一个根为（ ）',
    options: ['A. 0', 'B. 1', 'C. 2', 'D. 3'],
    answer: 'A',
    analysis: '把 x=3 代入方程，得 9-3(m+1)+m-2=0，解得 m=2。原方程变为 x²-3x=0，即 x(x-3)=0，所以另一个根为 0。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '参数方程已知一个根时，先代根求参数，再回到具体方程求另一个根。',
    steps: [
      {
        step: 1,
        title: '代入已知根',
        content: '因为 3 是方程的一个根，所以把 x=3 代入原方程。',
      },
      {
        step: 2,
        title: '求出参数',
        content: '得到 9-3(m+1)+m-2=0，化简得 m=2。',
        highlight: true,
      },
      {
        step: 3,
        title: '回代求另一根',
        content: '原方程化为 x²-3x=0，即 x(x-3)=0，所以另一个根是 0。',
      },
    ],
    keyPoints: ['参数方程', '根的定义', '回代验证'],
    commonMistakes: ['求出 m 后忘记再求另一根', '把已知一个根当成根和使用'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_045',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_008',
    type: 'single_choice',
    content: '点 P 在⊙O 外，PA、PB 分别切⊙O 于 A、B。若 ∠APB=50°，则 ∠AOB 的度数为（ ）',
    options: ['A. 50°', 'B. 100°', 'C. 130°', 'D. 150°'],
    answer: 'C',
    analysis: '两条切线所夹角与所对圆心角互补，所以 ∠AOB=180°-50°=130°。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '圆综合题看到“外点引两条切线”，就要想到切线角和圆心角互补这一条桥梁关系。',
    steps: [
      {
        step: 1,
        title: '识别基本模型',
        content: 'PA、PB 是从圆外一点 P 向圆引出的两条切线。',
      },
      {
        step: 2,
        title: '调用切线角性质',
        content: '两条切线所夹角与所对圆心角互补，所以 ∠APB+∠AOB=180°。',
        highlight: true,
      },
      {
        step: 3,
        title: '代入求值',
        content: '∠AOB=180°-50°=130°。',
      },
    ],
    keyPoints: ['切线性质', '圆心角', '外点引切线'],
    commonMistakes: ['误把切线夹角和圆心角看成相等', '忘记使用互补关系'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_046',
    chapterId: 'ch3',
    knowledgePointId: 'kp9_015',
    type: 'fill_blank',
    content: '四边形 ABCD 内接于同一圆，且 ∠A = 2∠C，则 ∠A = ____。',
    answer: '120°',
    analysis: '圆内接四边形对角互补，所以 ∠A+∠C=180°。又因为 ∠A=2∠C，所以 3∠C=180°，得 ∠C=60°，从而 ∠A=120°。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '圆内接四边形综合题先抓“对角互补”，再把角之间的数量关系代进去联立。',
    steps: [
      {
        step: 1,
        title: '列出圆内接四边形性质',
        content: '因为四边形 ABCD 内接于同一圆，所以 ∠A+∠C=180°。',
      },
      {
        step: 2,
        title: '结合角的数量关系',
        content: '已知 ∠A=2∠C，代入得 2∠C+∠C=180°。',
        highlight: true,
      },
      {
        step: 3,
        title: '解出角度',
        content: '可得 ∠C=60°，因此 ∠A=120°。',
      },
    ],
    keyPoints: ['圆内接四边形', '对角互补', '角度方程'],
    commonMistakes: ['只用到倍数关系，没有先写互补', '算出 ∠C 后忘记继续求 ∠A'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_047',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_017',
    type: 'single_choice',
    content: '在 △ABC 中，DE∥BC，点 D、E 分别在 AB、AC 上。若 AD:AB=2:3，且 DE=6，则 BC 的长为（ ）',
    options: ['A. 8', 'B. 9', 'C. 10', 'D. 12'],
    answer: 'B',
    analysis: '因为 DE∥BC，所以 △ADE∼△ABC，且相似比 AD:AB=DE:BC=2:3。由 DE=6，得 BC=9。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '相似综合题先通过平行找相似，再把线段比和对应边联系起来。',
    steps: [
      {
        step: 1,
        title: '判定三角形相似',
        content: '由 DE∥BC，可得 ∠ADE=∠ABC，∠AED=∠ACB，所以 △ADE∼△ABC。',
      },
      {
        step: 2,
        title: '写出对应边比',
        content: '相似比为 AD:AB=DE:BC=2:3。',
        highlight: true,
      },
      {
        step: 3,
        title: '求对应边长度',
        content: '因为 DE=6，所以 BC=6×3/2=9。',
      },
    ],
    keyPoints: ['平行判相似', '对应边比', '相似应用'],
    commonMistakes: ['相似后把对应边写反', '看到比例线段但没先判相似'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_048',
    chapterId: 'ch4',
    knowledgePointId: 'kp9_020',
    type: 'fill_blank',
    content: '在 Rt△ABC 中，∠C=90°，若 tanA=3/4，且角 A 的对边 BC=12，则斜边 AB=____。',
    answer: '20',
    analysis: '由 tanA=BC/AC=3/4，可设 BC:AC=3:4。已知 BC=12，对应 3 份，所以每份为 4，AC=16。由勾股定理得 AB=20。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '三角函数综合题最稳的思路是先由函数值构造边比，再结合已知长度落到具体数值。',
    steps: [
      {
        step: 1,
        title: '由正切值构造边比',
        content: '因为 tanA=3/4，所以角 A 的对边 BC 与邻边 AC 的比为 3:4。',
      },
      {
        step: 2,
        title: '求出另一条直角边',
        content: '已知 BC=12，对应 3 份，所以每份为 4，故 AC=16。',
        highlight: true,
      },
      {
        step: 3,
        title: '利用勾股定理求斜边',
        content: 'AB=√(12²+16²)=20。',
      },
    ],
    keyPoints: ['正切定义', '边比构造', '勾股定理'],
    commonMistakes: ['把 tanA 对应边比写反', '求出 AC 后忘记继续求斜边'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_049',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_021',
    type: 'single_choice',
    content: '函数 y=-6/x 的图像位于（ ）',
    options: ['A. 第一、三象限', 'B. 第二、四象限', 'C. 第一、二象限', 'D. 第三、四象限'],
    answer: 'B',
    analysis: '反比例函数中 k<0 时，图像位于第二、四象限。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '反比例函数图像先看 k 的正负。',
    steps: [
      {
        step: 1,
        title: '确定参数符号',
        content: '这里 k=-6<0。',
      },
      {
        step: 2,
        title: '对应象限',
        content: 'k<0 时图像在第二、四象限。',
        highlight: true,
      },
    ],
    keyPoints: ['反比例函数图像', 'k 的符号'],
    commonMistakes: ['把正负象限关系记反'],
  },
  {
    id: 'g9_q_050',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_022',
    type: 'fill_blank',
    content: '若反比例函数 y=k/x 经过点 (2,-4)，则 k=____。',
    answer: '-8',
    analysis: '点在双曲线上，直接用 k=xy，可得 k=2×(-4)=-8。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '过点求参数，先想 k=xy。',
    steps: [
      {
        step: 1,
        title: '代入点坐标',
        content: '因为点 (2,-4) 在双曲线上，所以 k=2×(-4)。',
        highlight: true,
      },
      {
        step: 2,
        title: '求出参数',
        content: '得到 k=-8。',
      },
    ],
    keyPoints: ['k=xy', '待定系数'],
    commonMistakes: ['坐标相乘时忽略负号'],
  },
  {
    id: 'g9_q_051',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_023',
    type: 'judge',
    content: '点 P 在函数 y=5/x 的图像上，则点 P 与坐标轴围成的矩形面积一定为 5。',
    answer: '正确',
    analysis: '因为点在 y=5/x 上，所以 xy=5，矩形面积的绝对值就是 5。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '面积题看到反比例函数，就先把面积和 xy 联系起来。',
    steps: [
      {
        step: 1,
        title: '写出函数关系',
        content: '由 y=5/x，可得 xy=5。',
      },
      {
        step: 2,
        title: '转化面积',
        content: '与坐标轴围成的矩形面积常写成 |xy|，所以面积为 5。',
        highlight: true,
      },
    ],
    keyPoints: ['面积定值', 'xy 与 k 的关系'],
    commonMistakes: ['知道是面积题，却没先写成 xy'],
  },
  {
    id: 'g9_q_052',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_022',
    type: 'single_choice',
    content: '若双曲线 y=k/x 经过点 (-3,2)，则 k 的值为（ ）',
    options: ['A. -6', 'B. -1', 'C. 1', 'D. 6'],
    answer: 'A',
    analysis: '由 k=xy，可得 k=(-3)×2=-6。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '点在反比例函数图像上时，参数题最直接的入口就是坐标乘积。',
    steps: [
      {
        step: 1,
        title: '写出关系式',
        content: '点在双曲线上时，有 k=xy。',
      },
      {
        step: 2,
        title: '代入坐标',
        content: '代入 (-3,2)，得 k=(-3)×2=-6。',
        highlight: true,
      },
    ],
    keyPoints: ['k=xy', '参数求解'],
    commonMistakes: ['忘记处理负号', '把点代进 y=k/x 时移项出错'],
  },
  {
    id: 'g9_q_053',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_023',
    type: 'fill_blank',
    content: '点 P(a,b) 在双曲线 y=12/x 上，且与坐标轴围成矩形面积为 S，则 S=____。',
    answer: '12',
    analysis: '点在 y=12/x 上，所以 ab=12。矩形面积 S=|ab|=12。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '字母题也不用怕，面积还是先转成 ab，再利用双曲线关系。',
    steps: [
      {
        step: 1,
        title: '写出点坐标关系',
        content: '因为点 P(a,b) 在 y=12/x 上，所以 ab=12。',
      },
      {
        step: 2,
        title: '转成面积',
        content: '矩形面积 S=|ab|，因此 S=12。',
        highlight: true,
      },
    ],
    keyPoints: ['面积定值', '字母参数'],
    commonMistakes: ['看到字母就不敢下手', '面积题没先写成乘积形式'],
  },
  {
    id: 'g9_q_054',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_024',
    type: 'single_choice',
    content: '已知反比例函数 y=k/x 的图像经过点 (1,6)，则它的解析式是（ ）',
    options: ['A. y=6x', 'B. y=6/x', 'C. y=-6/x', 'D. y=x/6'],
    answer: 'B',
    analysis: '由点 (1,6) 在图像上，可得 k=1×6=6，所以解析式为 y=6/x。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '先求 k，再回到标准式 y=k/x。',
    steps: [
      {
        step: 1,
        title: '求参数',
        content: '由点 (1,6) 得 k=1×6=6。',
        highlight: true,
      },
      {
        step: 2,
        title: '写出解析式',
        content: '因此函数解析式为 y=6/x。',
      },
    ],
    keyPoints: ['待定系数法', '标准式'],
    commonMistakes: ['求出 k 后没回到 y=k/x', '把反比例函数误写成一次函数'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_055',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_025',
    type: 'single_choice',
    content: '点 A 在双曲线 y=8/x 上，且以点 A 和坐标轴围成的矩形面积为 S。若点 A 在第一象限，则 S 的值为（ ）',
    options: ['A. 4', 'B. 6', 'C. 8', 'D. 随点 A 位置变化'],
    answer: 'C',
    analysis: '因为点 A 在双曲线 y=8/x 上，所以 xy=8。矩形面积 S=xy=8，因此面积是定值 8。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '反比例函数综合题里最经典的入口就是“面积定值”，先别被点的位置变化吓住。',
    steps: [
      {
        step: 1,
        title: '抓住双曲线条件',
        content: '点 A 在 y=8/x 上，所以有 xy=8。',
      },
      {
        step: 2,
        title: '转化面积',
        content: '第一象限内 x、y 都为正，矩形面积 S=xy=8。',
        highlight: true,
      },
      {
        step: 3,
        title: '判断是否变化',
        content: '无论点 A 在第一象限的哪个位置，只要还在该双曲线上，面积都保持为 8。',
      },
    ],
    keyPoints: ['面积定值', '第一象限', '综合判断'],
    commonMistakes: ['看到点在动就以为面积也在变', '没注意第一象限可以去掉绝对值'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_056',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_025',
    type: 'fill_blank',
    content: '双曲线 y=k/x 经过点 (2,3)。若点 A(2,3)、点 B(3,0)、点 C(0,3) 构成图形，则三角形 ABC 的面积为____。',
    answer: '3',
    analysis: '由坐标面积法可得三角形 ABC 的面积为 3。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '这类综合题要先稳住点坐标，再从坐标几何角度算面积，不必一开始就被双曲线本身困住。',
    steps: [
      {
        step: 1,
        title: '确认点坐标关系',
        content: '点 A(2,3) 在双曲线上，可先得到 k=6，确认题目给出的点与函数关系一致。',
      },
      {
        step: 2,
        title: '转成坐标面积问题',
        content: '接着不再纠缠双曲线本身，而是利用 A、B、C 三点坐标求三角形面积。',
      },
      {
        step: 3,
        title: '求出面积',
        content: '以 AC 为底，AC=2，点 B 到直线 AC 的距离为 3，所以面积为 1/2×2×3=3。',
        highlight: true,
      },
    ],
    keyPoints: ['坐标与面积', '参数确认', '函数综合'],
    commonMistakes: ['只盯着双曲线不回到坐标几何', '面积计算时底和高选取混乱'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_057',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_021',
    type: 'judge',
    content: '反比例函数图像上的点越靠近坐标轴，对应的函数值绝对值一定越小。',
    answer: '错误',
    analysis: '靠近不同坐标轴时变化情况不同，不能笼统说函数值绝对值一定更小。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '反比例函数图像的变化要结合靠近哪条坐标轴来理解，不能一句话绝对化。',
    steps: [
      {
        step: 1,
        title: '分清靠近哪条坐标轴',
        content: '靠近 x 轴意味着 |y| 变小，靠近 y 轴则往往意味着 |y| 变大。',
      },
      {
        step: 2,
        title: '判断命题',
        content: '题目没有区分具体情况，所以说法错误。',
        highlight: true,
      },
    ],
    keyPoints: ['图像理解', '绝对值变化'],
    commonMistakes: ['把反比例函数变化规律绝对化', '忽略不同坐标轴对应的不同趋势'],
  },
  {
    id: 'g9_q_058',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_024',
    type: 'fill_blank',
    content: '若双曲线 y=k/x 经过点 (m,2) 和 (1,8)，则 m=____。',
    answer: '4',
    analysis: '由点 (1,8) 可得 k=8。再由点 (m,2) 在图像上，可得 2m=8，所以 m=4。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '多点参数题先用最简单的点求 k，再带回求未知字母。',
    steps: [
      {
        step: 1,
        title: '先求参数',
        content: '由点 (1,8) 得 k=1×8=8。',
        highlight: true,
      },
      {
        step: 2,
        title: '再求未知字母',
        content: '点 (m,2) 在图像上，所以 2m=8，解得 m=4。',
      },
    ],
    keyPoints: ['多点参数题', 'k=xy'],
    commonMistakes: ['两个点一起列复杂方程', '求出 k 后忘记继续求 m'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_059',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_025',
    type: 'fill_blank',
    content: '在第一象限内，双曲线 y=6/x 与直线 y=x+1 交于点 A，则点 A 的坐标为____。',
    answer: '(2,3)',
    analysis: '联立 y=6/x 与 y=x+1，得 6/x=x+1，即 x²+x-6=0。解得 x=2 或 x=-3。因为点 A 在第一象限，所以 x=2，进而 y=3。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '反比例函数综合题遇到“和另一条直线相交”，先联立方程，再用象限条件筛掉无效解。',
    steps: [
      {
        step: 1,
        title: '联立两个函数关系',
        content: '因为点 A 同时在双曲线和直线上，所以有 6/x=x+1。',
      },
      {
        step: 2,
        title: '化为方程求 x',
        content: '移项整理得 x²+x-6=0，分解因式得 (x+3)(x-2)=0，所以 x=2 或 x=-3。',
        highlight: true,
      },
      {
        step: 3,
        title: '结合象限确定点坐标',
        content: '第一象限要求 x>0，所以取 x=2，再代入 y=x+1 得 y=3，因此 A=(2,3)。',
      },
    ],
    keyPoints: ['联立方程', '象限筛选', '函数交点'],
    commonMistakes: ['联立后只求出 x 不回代求 y', '忘记用“第一象限”排除无效解'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_060',
    chapterId: 'ch5',
    knowledgePointId: 'kp9_025',
    type: 'fill_blank',
    content: '点 A(x,y) 在第一象限的双曲线 y=k/x 上，过点 A 分别向两坐标轴作垂线，围成矩形 OABC。若矩形 OABC 的周长为 16，且 x-y=4，则 k=____。',
    answer: '12',
    analysis: '由矩形周长为 16，得 2(x+y)=16，所以 x+y=8。再结合 x-y=4，解得 x=6，y=2。因为点 A 在 y=k/x 上，所以 k=xy=12。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '这类综合题要把“矩形条件”和“函数条件”拆开：先用周长与坐标关系解出 x、y，再回到 k=xy。',
    steps: [
      {
        step: 1,
        title: '由周长得到和',
        content: '矩形 OABC 的周长为 16，所以 2(x+y)=16，即 x+y=8。',
      },
      {
        step: 2,
        title: '联立坐标关系求 x、y',
        content: '再结合 x-y=4，联立方程组可得 x=6，y=2。',
        highlight: true,
      },
      {
        step: 3,
        title: '回到反比例函数求参数',
        content: '点 A 在双曲线上，所以 k=xy=6×2=12。',
      },
    ],
    keyPoints: ['矩形周长', '二元一次方程组', 'k=xy'],
    commonMistakes: ['只列出 x+y=8 就停下', '求出 x、y 后忘记再回到 k'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_061',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_026',
    type: 'single_choice',
    content: '一组数据为 2，3，3，5，10，则这组数据的众数是（ ）',
    options: ['A. 2', 'B. 3', 'C. 5', 'D. 10'],
    answer: 'B',
    analysis: '3 出现了两次，出现次数最多，所以众数是 3。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '众数只看谁出现得最多，不用求平均。',
    steps: [
      {
        step: 1,
        title: '统计出现次数',
        content: '数据 3 出现了两次，其余数只出现一次。',
      },
      {
        step: 2,
        title: '确定众数',
        content: '出现次数最多的数据是 3，所以众数为 3。',
        highlight: true,
      },
    ],
    keyPoints: ['众数', '统计量辨认'],
    commonMistakes: ['把众数和中位数混淆'],
  },
  {
    id: 'g9_q_062',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_026',
    type: 'fill_blank',
    content: '将数据 1，4，6，8，9 按从小到大排列后，其中位数是____。',
    answer: '6',
    analysis: '共 5 个数据，排好序后正中间的第 3 个数是 6。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '求中位数先排序，再看中间位置。',
    steps: [
      {
        step: 1,
        title: '确认数据顺序',
        content: '题目中的数据已经按从小到大排列。',
      },
      {
        step: 2,
        title: '找中间位置',
        content: '5 个数据的中位数是第 3 个数，所以答案是 6。',
        highlight: true,
      },
    ],
    keyPoints: ['中位数', '排序'],
    commonMistakes: ['没排序就直接找中位数'],
  },
  {
    id: 'g9_q_063',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_027',
    type: 'judge',
    content: '两组数据平均数相同，方差较小的那组数据更稳定。',
    answer: '正确',
    analysis: '方差反映数据波动大小，方差越小，数据越稳定。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '稳定性看波动，方差越小越稳定。',
    steps: [
      {
        step: 1,
        title: '明确方差含义',
        content: '方差描述的是数据的离散程度和波动大小。',
      },
      {
        step: 2,
        title: '判断稳定性',
        content: '波动越小越稳定，所以方差较小的一组更稳定。',
        highlight: true,
      },
    ],
    keyPoints: ['方差', '稳定性'],
    commonMistakes: ['只记“越小越好”，不会和稳定性联系'],
  },
  {
    id: 'g9_q_064',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_028',
    type: 'single_choice',
    content: '研究某班五次模拟考试平均分的变化趋势，最适合选用的统计图是（ ）',
    options: ['A. 条形图', 'B. 扇形图', 'C. 折线图', 'D. 频数分布直方图'],
    answer: 'C',
    analysis: '折线图更适合展示随时间或顺序变化的趋势。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '先看题目想突出“比较大小”还是“变化趋势”。',
    steps: [
      {
        step: 1,
        title: '抓住题目关键词',
        content: '题目强调的是“五次考试平均分的变化趋势”。',
      },
      {
        step: 2,
        title: '排除不匹配图表',
        content: '扇形图适合表示占比，条形图更适合静态比较大小，频数分布直方图主要用于分布情况分析。',
      },
      {
        step: 3,
        title: '匹配图表类型',
        content: '折线图最适合表示随时间变化的趋势，所以选 C。',
        highlight: true,
      },
    ],
    keyPoints: ['折线图', '趋势判断'],
    commonMistakes: ['只要看到成绩就本能选条形图'],
  },
  {
    id: 'g9_q_065',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_027',
    type: 'fill_blank',
    content: '甲、乙两组数据的平均数都为 8，若甲组方差比乙组方差小，则更稳定的是____组。',
    answer: '甲',
    analysis: '平均数相同的情况下，方差越小，说明波动越小，因此甲组更稳定。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '比较稳定性时，平均数相同就直接比方差。',
    steps: [
      {
        step: 1,
        title: '确认比较前提',
        content: '两组数据平均数相同，所以稳定性主要看波动大小。',
      },
      {
        step: 2,
        title: '比较方差',
        content: '甲组方差更小，所以甲组波动更小，更稳定。',
        highlight: true,
      },
    ],
    keyPoints: ['方差比较', '稳定性判断'],
    commonMistakes: ['把平均数高低和稳定性混为一谈'],
  },
  {
    id: 'g9_q_066',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_029',
    type: 'fill_blank',
    content: '一个不透明袋中装有 2 个红球和 3 个白球，随机摸出 1 个球，摸到红球的概率是____。',
    answer: '2/5',
    analysis: '共有 5 个球，其中红球 2 个，所以摸到红球的概率为 2/5。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '古典概率先数总结果，再数有利结果。',
    steps: [
      {
        step: 1,
        title: '统计总结果数',
        content: '袋中共有 2+3=5 个球。',
      },
      {
        step: 2,
        title: '统计有利结果数',
        content: '摸到红球是有利结果，共有 2 个。',
      },
      {
        step: 3,
        title: '代入古典概率公式',
        content: '概率 = 有利结果数 ÷ 全部等可能结果数 = 2/5。',
      },
      {
        step: 4,
        title: '写出结果',
        content: '因此摸到红球的概率为 2/5。',
        highlight: true,
      },
    ],
    keyPoints: ['古典概率', '有利结果数/总结果数'],
    commonMistakes: ['把红球数直接当成概率', '总结果数数错'],
  },
  {
    id: 'g9_q_067',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_029',
    type: 'single_choice',
    content: '同时掷两枚质地均匀的硬币，用列表法统计结果，则“两枚都正面朝上”的概率是（ ）',
    options: ['A. 1/2', 'B. 1/3', 'C. 1/4', 'D. 3/4'],
    answer: 'C',
    analysis: '两枚硬币共有 4 种等可能结果：正正、正反、反正、反反，其中只有 1 种符合条件，所以概率为 1/4。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '两个独立对象的问题，先把全部等可能结果列全。',
    steps: [
      {
        step: 1,
        title: '列出全部结果',
        content: '共有正正、正反、反正、反反 4 种等可能结果。',
      },
      {
        step: 2,
        title: '统计有利结果',
        content: '只有“正正”这一种符合条件。',
      },
      {
        step: 3,
        title: '求概率',
        content: '所以概率为 1/4。',
        highlight: true,
      },
    ],
    keyPoints: ['列表法', '等可能结果'],
    commonMistakes: ['把正反和反正看成同一种结果'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_068',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_028',
    type: 'fill_blank',
    content: '某班共有 40 名学生，扇形图显示参加篮球社团的学生占全班的 25%，则参加篮球社团的学生有____人。',
    answer: '10',
    analysis: '40×25%=10，所以参加篮球社团的学生有 10 人。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '图表综合题先把占比转成具体人数，再继续后续判断。',
    steps: [
      {
        step: 1,
        title: '找到总量和占比',
        content: '题目给出全班 40 人，篮球社团占 25%。',
      },
      {
        step: 2,
        title: '换算成具体人数',
        content: '参加篮球社团人数为 40×25%=10。',
        highlight: true,
      },
    ],
    keyPoints: ['扇形图', '百分比换算'],
    commonMistakes: ['只看出 25%，却没回到总人数'],
  },
  {
    id: 'g9_q_069',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_030',
    type: 'fill_blank',
    content: '某班学生最喜欢的运动项目统计如下：篮球 12 人，羽毛球 10 人，乒乓球 8 人。若从中随机抽取 1 名学生，抽到最喜欢羽毛球的学生的概率是____。',
    answer: '1/3',
    analysis: '总人数为 12+10+8=30，喜欢羽毛球的有 10 人，所以概率为 10/30=1/3。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '这类统计与概率综合题先把图表或数据整理成总人数和目标人数，再求概率。',
    steps: [
      {
        step: 1,
        title: '求总人数',
        content: '总人数为 12+10+8=30。',
      },
      {
        step: 2,
        title: '找有利结果数',
        content: '喜欢羽毛球的学生有 10 人。',
      },
      {
        step: 3,
        title: '写出概率',
        content: '概率为 10/30=1/3。',
        highlight: true,
      },
    ],
    keyPoints: ['统计与概率综合', '总量与有利结果'],
    commonMistakes: ['只读出目标人数，忘记先算总人数'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_070',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_030',
    type: 'single_choice',
    content: '某校随机调查了 50 名学生每天体育锻炼时间，发现其中 20 人锻炼时间不少于 1 小时。若从这 50 名学生中随机抽取 1 人，则抽到锻炼时间不少于 1 小时的学生的概率是（ ）',
    options: ['A. 2/5', 'B. 1/2', 'C. 3/5', 'D. 4/5'],
    answer: 'A',
    analysis: '符合条件的学生有 20 人，总人数为 50 人，所以概率为 20/50=2/5。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '先从统计调查中读出符合条件的人数，再用古典概率模型表达。',
    steps: [
      {
        step: 1,
        title: '提取有效数据',
        content: '调查样本共有 50 人，其中符合条件的有 20 人。',
      },
      {
        step: 2,
        title: '建立概率模型',
        content: '把 50 人视为等可能抽取对象，则概率为 20/50。',
      },
      {
        step: 3,
        title: '化简结果',
        content: '20/50=2/5，所以选 A。',
        highlight: true,
      },
    ],
    keyPoints: ['样本数据读取', '古典概率'],
    commonMistakes: ['把 20 直接当答案', '忘记化简概率结果'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_071',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_030',
    type: 'fill_blank',
    content: '某校对九年级学生参加课后社团情况进行调查，条形图显示参加科技社团、文学社团、篮球社团的人数比为 3:2:5，已知总人数为 50。若从参加社团的学生中随机抽取 1 人，则抽到参加文学社团学生的概率是____。',
    answer: '1/5',
    analysis: '人数比总份数为 3+2+5=10，每份对应 50÷10=5 人。文学社团人数为 2×5=10 人，所以概率为 10/50=1/5。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格图表综合题常先把“比例信息”还原成具体人数，再进入概率模型。',
    steps: [
      {
        step: 1,
        title: '求总份数',
        content: '人数比为 3:2:5，所以总份数为 3+2+5=10。',
      },
      {
        step: 2,
        title: '换算每份人数',
        content: '总人数为 50，所以每份对应 50÷10=5 人。',
      },
      {
        step: 3,
        title: '求文学社团人数',
        content: '文学社团人数为 2×5=10 人。',
      },
      {
        step: 4,
        title: '建立概率模型',
        content: '从 50 人中随机抽取 1 人，抽到文学社团学生的概率为 10/50=1/5。',
        highlight: true,
      },
    ],
    keyPoints: ['比例还原人数', '图表信息转数量', '古典概率'],
    commonMistakes: ['看到比值后不先求每份人数', '把 2/10 直接当最终答案却忘了和总人数对应'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_072',
    chapterId: 'ch6',
    knowledgePointId: 'kp9_029',
    type: 'single_choice',
    content: '一个转盘被平均分成 4 个区域，分别标有数字 1，2，3，4。连续转动两次，若用树状图统计结果，则两次所得数字之和大于 5 的概率是（ ）',
    options: ['A. 3/8', 'B. 5/16', 'C. 3/16', 'D. 1/4'],
    answer: 'A',
    analysis: '连续转动两次共有 4×4=16 种等可能结果。数字和大于 5 的有 (2,4)、(3,3)、(3,4)、(4,2)、(4,3)、(4,4) 共 6 种，所以概率为 6/16=3/8。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '分步概率综合题要先用树状图或有序数对把全部结果列全，再按条件筛选有利结果。',
    steps: [
      {
        step: 1,
        title: '统计全部等可能结果',
        content: '连续转动两次，每次有 4 种可能，因此共有 4×4=16 种等可能结果。',
      },
      {
        step: 2,
        title: '筛选和大于 5 的结果',
        content: '满足条件的有 (2,4)、(3,3)、(3,4)、(4,2)、(4,3)、(4,4)，共 6 种。',
      },
      {
        step: 3,
        title: '求出概率',
        content: '概率为 6/16=3/8，所以选 A。',
        highlight: true,
      },
    ],
    keyPoints: ['树状图/有序数对', '分步概率', '条件筛选'],
    commonMistakes: ['把 (2,4) 和 (4,2) 误认为同一种结果', '只数到部分满足条件的组合'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_073',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_031',
    type: 'single_choice',
    content: '在圆的切线题中，若切点为 P，最常优先补的辅助线是（ ）',
    options: ['A. 连接圆心与切点 P', 'B. 连接圆心与弦的另一个端点', 'C. 任取一条过 P 的平行线', 'D. 连接圆心与圆外一点'],
    answer: 'A',
    analysis: '切线题的常见入口是连接圆心与切点，因为半径垂直切线。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '看到切线，先想半径垂直切线。',
    steps: [
      {
        step: 1,
        title: '抓住切线条件',
        content: '题目已经明确是圆的切线题。',
      },
      {
        step: 2,
        title: '选择常用辅助线',
        content: '连接圆心与切点，可以立刻利用“半径垂直切线”。',
        highlight: true,
      },
    ],
    keyPoints: ['切线', '半径', '辅助线'],
    commonMistakes: ['看到切线却没有先连半径'],
  },
  {
    id: 'g9_q_074',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_033',
    type: 'judge',
    content: '在四边形综合题中，若已知两组对边分别平行，就可以先利用平行线带出的角关系寻找相似入口。',
    answer: '正确',
    analysis: '平行线常带出同位角、内错角相等，是几何综合题中建立相似的重要入口。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '平行关系往往不是终点，而是为角关系和相似服务。',
    steps: [
      {
        step: 1,
        title: '识别平行关系',
        content: '两组对边平行时，图中角关系会明显增多。',
      },
      {
        step: 2,
        title: '判断作用',
        content: '这些角关系常帮助建立相似，所以命题正确。',
        highlight: true,
      },
    ],
    keyPoints: ['平行线角关系', '相似入口'],
    commonMistakes: ['知道平行但不会把它转成角关系'],
  },
  {
    id: 'g9_q_075',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_032',
    type: 'fill_blank',
    content: '圆与相似综合题里，若想建立相似三角形，常见的第一步是先____。',
    answer: '追角找到对应角相等',
    analysis: '圆综合题常先利用圆周角、切线或弧弦关系追出角，再建立相似三角形。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '圆与相似综合题最稳的入口通常不是算边，而是先追角。',
    steps: [
      {
        step: 1,
        title: '确定当前目标',
        content: '题目想建立相似三角形。',
      },
      {
        step: 2,
        title: '寻找入口',
        content: '圆中的角关系最容易成为相似判定条件，所以应先追角。',
        highlight: true,
      },
    ],
    keyPoints: ['圆周角', '追角', '相似判定'],
    commonMistakes: ['想建相似却不先处理角关系'],
  },
  {
    id: 'g9_q_076',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_033',
    type: 'single_choice',
    content: '在平行四边形 ABCD 中，若要证明某两个三角形相似，最先值得利用的是（ ）',
    options: ['A. 对边平行带来的角关系', 'B. 所有边都相等', 'C. 所有角都是直角', 'D. 随机延长一条边'],
    answer: 'A',
    analysis: '平行四边形最稳定的性质之一是两组对边平行，可快速带出角关系，从而为相似做准备。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '平行四边形综合题先抓最稳定的平行关系。',
    steps: [
      {
        step: 1,
        title: '识别核心图形',
        content: '已知图形是平行四边形。',
      },
      {
        step: 2,
        title: '提取核心性质',
        content: '平行四边形的两组对边平行，最适合先用来追角。',
      },
      {
        step: 3,
        title: '明确后续用途',
        content: '角关系一旦理清，后面就更容易判相似、求边比或做面积转化。',
      },
      {
        step: 4,
        title: '确定答案',
        content: '因此最先值得利用的是平行带来的角关系，选 A。',
        highlight: true,
      },
    ],
    keyPoints: ['平行四边形', '平行关系', '相似'],
    commonMistakes: ['一看到平行四边形就只想到对边相等，忽略平行角关系'],
  },
  {
    id: 'g9_q_077',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_034',
    type: 'fill_blank',
    content: '几何最值题中，若要求某个面积的最小值，通常应先把面积写成可比较的____。',
    answer: '表达式',
    analysis: '最值题的关键是先把长度或面积转化为表达式，再分析变量和定量。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '最值题不要一开始就猜结果，先把量表达出来。',
    steps: [
      {
        step: 1,
        title: '明确最值分析前提',
        content: '最值分析必须先知道这个量怎样随变量变化。',
      },
      {
        step: 2,
        title: '确定入口',
        content: '所以应先把面积写成可比较、可计算的表达式。',
        highlight: true,
      },
    ],
    keyPoints: ['最值题', '表达式', '变量与定量'],
    commonMistakes: ['还没建表达式就开始讨论最值'],
  },
  {
    id: 'g9_q_078',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_035',
    type: 'judge',
    content: '几何存在性题中，如果点的位置可能变化，通常需要分类讨论，否则容易漏解。',
    answer: '正确',
    analysis: '存在性题往往因点的位置不同而对应不同关系，不分类就容易漏掉合法情况。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '存在性题的重点常不是计算，而是讨论是否分全了情况。',
    steps: [
      {
        step: 1,
        title: '识别题型特点',
        content: '存在性题常伴随位置变化和多种可能情形。',
      },
      {
        step: 2,
        title: '识别风险点',
        content: '点的位置变化后，图形关系和等式条件都可能跟着变化。',
      },
      {
        step: 3,
        title: '判断是否需要分类',
        content: '若不分类讨论，往往会漏掉一部分位置，所以命题正确。',
        highlight: true,
      },
    ],
    keyPoints: ['存在性', '分类讨论'],
    commonMistakes: ['只讨论一种图形位置就下结论'],
  },
  {
    id: 'g9_q_079',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_032',
    type: 'fill_blank',
    content: '如图，在圆 O 中，切线 PA 与过点 A 的弦 AB 相交成角。若要求与该角有关的线段比，常见思路是先由切线与圆的性质追出角，再建立____三角形。',
    answer: '相似',
    analysis: '圆与切线综合题常先用切线性质和圆周角关系追角，再构造相似三角形求线段比。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格圆综合题常见主线就是“追角 → 相似 → 比例计算”。',
    steps: [
      {
        step: 1,
        title: '识别图形线索',
        content: '题目中同时出现圆、切线和弦，这通常说明要先处理角关系。',
      },
      {
        step: 2,
        title: '确定中间桥梁',
        content: '追角的目的不是停留在角，而是为后续建立相似三角形服务。',
      },
      {
        step: 3,
        title: '确定答案',
        content: '因此应建立相似三角形，再通过相似比计算线段关系。',
        highlight: true,
      },
    ],
    keyPoints: ['切线性质', '追角', '相似三角形'],
    commonMistakes: ['角追出来后没有继续回到相似主线'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_080',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_034',
    type: 'single_choice',
    content: '在 Rt△ABC 中，∠C=90°，点 P 在边 AB 上运动。若要求点 P 到直线 AC、BC 的距离和的最小值，以下哪种思路最值得优先尝试？（ ）',
    options: ['A. 先猜最小值再验证', 'B. 先把两段距离转化为面积或表达式再分析', 'C. 直接枚举点 P 的所有位置', 'D. 只画图不列式'],
    answer: 'B',
    analysis: '几何最值题更稳的入口是先把目标量转成可计算的表达式，常借助面积、垂线段或比例关系。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '几何最值题里，“先表达再比较”通常比“先猜结果”更可靠。',
    steps: [
      {
        step: 1,
        title: '识别题型',
        content: '题目问的是点运动过程中的最小值。',
      },
      {
        step: 2,
        title: '选择稳定入口',
        content: '最值题最稳的策略是先借助面积或垂线段把目标量写成表达式。',
      },
      {
        step: 3,
        title: '确定答案',
        content: '因此最值得优先尝试的是先转化为面积或表达式再分析，选 B。',
        highlight: true,
      },
    ],
    keyPoints: ['最值转化', '面积思想', '表达式'],
    commonMistakes: ['还没转化就开始凭图猜最值'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_081',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_035',
    type: 'single_choice',
    content: '在几何存在性题中，若点 P 可能在线段 AB 上、AB 的延长线上或线段内部不同位置，要避免漏解，最关键的是（ ）',
    options: ['A. 只讨论最常见的一种情况', 'B. 先分类讨论不同位置，再逐类验证条件', 'C. 直接默认点 P 在线段中点', 'D. 先把所有长度设成相等'],
    answer: 'B',
    analysis: '存在性题最核心的是分清不同位置带来的不同关系，分类讨论后再逐类验证，才能避免漏解。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '几何存在性题最怕“只看一种图形位置”，分类讨论是主线不是附加步骤。',
    steps: [
      {
        step: 1,
        title: '识别位置变化',
        content: '题目已经提示点 P 可能落在不同位置。',
      },
      {
        step: 2,
        title: '选择处理主线',
        content: '不同位置对应的关系式可能不同，所以必须先分类讨论。',
      },
      {
        step: 3,
        title: '确定答案',
        content: '逐类验证条件才能避免漏解，因此选 B。',
        highlight: true,
      },
    ],
    keyPoints: ['存在性', '分类讨论', '位置变化'],
    commonMistakes: ['只讨论一种位置', '分类后没有逐类验证条件'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_082',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_033',
    type: 'fill_blank',
    content: '在一个含平行四边形和三角形的综合图形中，若已知两组平行边，且要求两个三角形面积比，常见思路是先利用平行关系追角，再建立____三角形。',
    answer: '相似',
    analysis: '面积比题里若图中已有平行关系，常先追角建立相似，再利用相似比推出面积比。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '四边形与三角形综合题里，面积比常不是直接算，而是先通过相似比过渡。',
    steps: [
      {
        step: 1,
        title: '识别已有条件',
        content: '题目给出了两组平行边，这是追角和建立相似的典型入口。',
      },
      {
        step: 2,
        title: '找到面积比桥梁',
        content: '面积比往往先借相似比转化，再从边比过渡到面积比。',
      },
      {
        step: 3,
        title: '确定答案',
        content: '因此应先建立相似三角形。',
        highlight: true,
      },
    ],
    keyPoints: ['平行追角', '相似', '面积比'],
    commonMistakes: ['一看到面积比就直接硬算', '平行关系没有转成相似入口'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_083',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_032',
    type: 'single_choice',
    content: '如图，在圆 O 中，PA、PB 分别切圆于点 A、B，连接 AB。若要求证某两个三角形相似，最值得优先利用的是（ ）',
    options: ['A. PA=PB 与圆周角关系', 'B. OA=OB 与切线垂直半径关系', 'C. 任意连接圆心与圆外点', 'D. 先设所有线段相等'],
    answer: 'B',
    analysis: '切线题中先连接 OA、OB，可得 OA⊥PA，OB⊥PB，再结合 OA=OB 容易形成角关系和对应边关系，为相似做准备。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格圆切线综合题里，最稳的第一步通常是“连半径，造直角，追角”。',
    steps: [
      {
        step: 1,
        title: '抓住切线条件',
        content: 'PA、PB 都是切线，所以半径 OA、OB 分别垂直于 PA、PB。',
      },
      {
        step: 2,
        title: '补出稳定关系',
        content: '连接 OA、OB 后，不但得到两个直角，还能利用 OA=OB 形成更稳定的图形关系。',
      },
      {
        step: 3,
        title: '判断最优入口',
        content: '比起直接猜相似，先用半径与切线的垂直关系更容易追角和构造相似，因此选 B。',
        highlight: true,
      },
    ],
    keyPoints: ['切线', '半径', '追角', '相似入口'],
    commonMistakes: ['看到两条切线却不先连接半径', '想证相似却缺少角关系'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_084',
    chapterId: 'ch7',
    knowledgePointId: 'kp9_035',
    type: 'fill_blank',
    content: '在△ABC 中，点 P 在线段 BC 上运动。若题目要求“是否存在点 P，使得△ABP 与△ACP 的面积比为 1:2”，处理这类存在性问题时，最关键的第一步应是先____。',
    answer: '按点 P 的位置建立面积关系并分类讨论',
    analysis: '存在性题不能先凭感觉判断，要先根据点 P 在线段上的位置建立面积表达，再看条件能否成立；若位置可能变化，还要分类讨论。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '北京风格存在性题的主线通常不是直接求点，而是“先列关系，再判存在，再查是否漏情况”。',
    steps: [
      {
        step: 1,
        title: '识别题型目标',
        content: '题目不是直接求长度，而是判断某种面积比条件下点 P 是否存在。',
      },
      {
        step: 2,
        title: '建立几何量关系',
        content: '应先把 △ABP 与 △ACP 的面积与点 P 的位置联系起来，而不是先猜点在哪里。',
      },
      {
        step: 3,
        title: '明确存在性处理主线',
        content: '存在性题通常要先列关系，再按位置讨论并验证条件，所以第一步应是建立面积关系并分类讨论。',
        highlight: true,
      },
    ],
    keyPoints: ['存在性', '面积关系', '分类讨论'],
    commonMistakes: ['先凭图猜点的位置', '没建立关系就急着判断是否存在'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_085',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_036',
    type: 'fill_blank',
    content: '函数图像与 x 轴交点的横坐标，本质上就是对应方程的____。',
    answer: '根',
    analysis: '图像与 x 轴交点满足 y=0，所以横坐标就是对应方程的解。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '看到交点先想 y=0，看到 y=0 就回到方程根。',
    steps: [
      {
        step: 1,
        title: '抓住交点定义',
        content: '图像与 x 轴交点处，函数值为 0。',
      },
      {
        step: 2,
        title: '转化成方程',
        content: '所以横坐标就是对应方程的根。',
        highlight: true,
      },
    ],
    keyPoints: ['交点', 'y=0', '方程根'],
    commonMistakes: ['看到图像交点却没想到方程'],
  },
  {
    id: 'g9_q_086',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_040',
    type: 'judge',
    content: '处理中考压轴题时，一上来先把所有计算都铺开，比先判断题目主线更稳。',
    answer: '错误',
    analysis: '压轴题更稳的做法是先判断主线和层次，再决定从哪里下手；一开始就铺开计算往往会越做越乱。',
    difficulty: 'easy',
    points: 5,
    trainingStage: 'basic',
    thinking: '压轴题先拆题，不是先暴力开算。',
    steps: [
      {
        step: 1,
        title: '识别压轴题特点',
        content: '压轴题通常信息多、层次多，不适合第一步就全部展开。',
      },
      {
        step: 2,
        title: '判断更稳策略',
        content: '先判断主线和层次更稳，所以命题错误。',
        highlight: true,
      },
    ],
    keyPoints: ['压轴拆题', '主线判断'],
    commonMistakes: ['不拆题就直接算'],
  },
  {
    id: 'g9_q_087',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_037',
    type: 'single_choice',
    content: '若关于 x 的一元二次方程 x²-(m+1)x+m=0 有两个不相等的实数根，则参数 m 应满足的首要条件是（ ）',
    options: ['A. m>0', 'B. Δ>0', 'C. x>0', 'D. m<0'],
    answer: 'B',
    analysis: '题目要求方程有两个不相等的实数根，首要条件就是判别式 Δ>0。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '参数题先看题目要求的根的情况，再决定第一层条件。',
    steps: [
      {
        step: 1,
        title: '识别题目要求',
        content: '题目强调“有两个不相等的实数根”。',
      },
      {
        step: 2,
        title: '回到标准判别条件',
        content: '一元二次方程有两个不等实根时，首先要想到判别式 Δ>0。',
      },
      {
        step: 3,
        title: '对应到首要条件',
        content: '因此题目问“首要条件”时，答案就是 Δ>0。',
        highlight: true,
      },
    ],
    keyPoints: ['参数题', '判别式', '两个不等实根'],
    commonMistakes: ['还没列条件就开始猜 m 的范围'],
  },
  {
    id: 'g9_q_088',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_038',
    type: 'fill_blank',
    content: '代数题出现绝对值、参数或根的情况时，若不同情形会导致关系改变，通常应先进行____。',
    answer: '分类讨论',
    analysis: '当题目本身存在多种情形时，先分类讨论才不容易漏解。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '关系一旦可能变，就先问自己要不要分情况。',
    steps: [
      {
        step: 1,
        title: '识别多情形特征',
        content: '绝对值、参数、根的情况变化，都可能导致题目本身分情况。',
      },
      {
        step: 2,
        title: '确定处理主线',
        content: '因此通常应先分类讨论。',
        highlight: true,
      },
    ],
    keyPoints: ['分类讨论', '多情形'],
    commonMistakes: ['明明需要分类却只讨论一种情况'],
  },
  {
    id: 'g9_q_089',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_039',
    type: 'single_choice',
    content: '代数最值题中，若表达式结构较复杂，以下哪种做法更稳妥？（ ）',
    options: ['A. 直接猜最值', 'B. 先化简或转化结构，再分析范围', 'C. 只代几个特殊值试试', 'D. 直接放弃'],
    answer: 'B',
    analysis: '代数最值题通常先把结构化简清楚，再分析变量关系和取值范围，思路更稳。',
    difficulty: 'medium',
    points: 10,
    trainingStage: 'method',
    thinking: '最值题最怕结构没看清就开始猜结果。',
    steps: [
      {
        step: 1,
        title: '识别难点来源',
        content: '表达式结构复杂时，直接猜最值通常没有依据。',
      },
      {
        step: 2,
        title: '明确先后顺序',
        content: '最值题通常先把式子化简或转化，结构清楚后再看变量关系和范围。',
      },
      {
        step: 3,
        title: '选择稳妥入口',
        content: '因此更稳妥的做法是先化简或转化结构，再分析范围。',
        highlight: true,
      },
    ],
    keyPoints: ['最值', '结构化简', '范围分析'],
    commonMistakes: ['式子还没看清就开始试值'],
  },
  {
    id: 'g9_q_090',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_036',
    type: 'fill_blank',
    content: '若抛物线 y=x²-3x+2 与 x 轴交于 A、B 两点，则线段 AB 的长度为____。',
    answer: '1',
    analysis: '令 y=0，得 x²-3x+2=0，解得 x=1 或 x=2，所以 A、B 两点横坐标差的绝对值为 1。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '函数方程综合题里，要求交点长度，先把交点坐标求出来。',
    steps: [
      {
        step: 1,
        title: '转化成交点方程',
        content: '与 x 轴交点满足 y=0，所以方程为 x²-3x+2=0。',
      },
      {
        step: 2,
        title: '求出两交点横坐标',
        content: '解得 x=1 和 x=2。',
      },
      {
        step: 3,
        title: '计算线段长度',
        content: '因为两点都在 x 轴上，所以 AB=|2-1|=1。',
        highlight: true,
      },
    ],
    keyPoints: ['函数与方程综合', '交点', '线段长度'],
    commonMistakes: ['求出根后忘记回到线段长度', '把交点长度和横坐标值混淆'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_091',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_037',
    type: 'single_choice',
    content: '已知抛物线 y=x²-2mx+3 与 x 轴有两个不相等的交点，则参数 m 应满足（ ）',
    options: ['A. m>0', 'B. m²>3', 'C. m<3', 'D. m²<3'],
    answer: 'B',
    analysis: '由方程 x²-2mx+3=0 有两个不相等的实数根，得判别式 Δ=(-2m)²-4×1×3>0，即 4m²-12>0，所以 m²>3。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '参数综合题遇到“图像与 x 轴有两个交点”，本质还是先回到判别式。',
    steps: [
      {
        step: 1,
        title: '看清题目条件',
        content: '图像与 x 轴有两个不等交点，本质上对应一元二次方程有两个不等实根。',
      },
      {
        step: 2,
        title: '建立判别式条件',
        content: '因此要满足 Δ>0，即 (-2m)²-4×1×3>0。',
      },
      {
        step: 3,
        title: '化简参数范围',
        content: '得到 4m²-12>0，即 m²>3，所以选 B。',
        highlight: true,
      },
    ],
    keyPoints: ['参数题', '图像与方程', '判别式'],
    commonMistakes: ['把“两个交点”当成图像语言，却忘了回到方程条件'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_092',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_040',
    type: 'fill_blank',
    content: '压轴题如果一共有三问，通常更稳的策略是先把第____问中的主线提示做扎实，再进入后续综合问。',
    answer: '一',
    analysis: '压轴题常常是层层递进的，第一问通常承担“主线提示”作用，先做稳第一问能为后面铺路。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '压轴题不是一口气吃掉，而是先抓住最稳的一层关系。',
    steps: [
      {
        step: 1,
        title: '识别压轴题结构',
        content: '三问压轴题通常是逐层推进，不是三问彼此孤立。',
      },
      {
        step: 2,
        title: '选择更稳起点',
        content: '第一问往往是后面综合问的主线提示或基础关系。',
      },
      {
        step: 3,
        title: '确定答案',
        content: '因此通常应先把第一问做扎实，再进后续综合问。',
        highlight: true,
      },
    ],
    keyPoints: ['压轴拆解', '分层推进', '主线提示'],
    commonMistakes: ['跳过第一问直接做后面', '没抓住压轴题的层次结构'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_093',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_036',
    type: 'fill_blank',
    content: '已知抛物线 y=x²-(m+1)x+m 与 x 轴交于不同的两点 A、B，且 m>0，线段 AB 的长度为 3，则 m 的值为____。',
    answer: '4',
    analysis: '由方程 x²-(m+1)x+m=0 的两根为 A、B 两点横坐标。因为 AB=3，所以两根之差绝对值为 3。设两根为 x1,x2，则 (x1-x2)²=(x1+x2)²-4x1x2=(m+1)²-4m=(m-1)²。由 |x1-x2|=3 得 |m-1|=3，解得 m=4 或 m=-2。结合题设 m>0，得到 m=4。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '函数方程综合里，交点距离常要回到两根关系，不一定每次都重新硬解方程。',
    steps: [
      {
        step: 1,
        title: '把交点长度转成根的关系',
        content: 'A、B 两点在 x 轴上，所以 AB 等于对应方程两根之差的绝对值。',
      },
      {
        step: 2,
        title: '利用根与系数关系',
        content: '由 x²-(m+1)x+m=0 可得 x1+x2=m+1，x1x2=m，因此 (x1-x2)²=(m+1)²-4m=(m-1)²。',
      },
      {
        step: 3,
        title: '代入长度条件',
        content: '因为 |x1-x2|=3，所以 |m-1|=3，解得 m=4 或 m=-2。',
      },
      {
        step: 4,
        title: '确定题目答案',
        content: '结合题设 m>0，得到 m=4。',
        highlight: true,
      },
    ],
    keyPoints: ['函数与方程综合', '根与系数关系', '交点距离'],
    commonMistakes: ['求交点长度时只会重新求根', '忘记交点长度就是两根之差的绝对值'],
    district: '北京',
    examType: '中考风格改写',
  },
  {
    id: 'g9_q_094',
    chapterId: 'ch8',
    knowledgePointId: 'kp9_038',
    type: 'single_choice',
    content: '关于 x 的方程 |x-2| = m 有解，且这些解中恰有一个满足 x>3，则参数 m 的取值是（ ）',
    options: ['A. 1', 'B. 2', 'C. 3', 'D. 4'],
    answer: 'B',
    analysis: '方程 |x-2|=m 有解需 m≥0。解为 x=2+m 或 x=2-m。若恰有一个解满足 x>3，则需 2+m>3 且 2-m≤3。前者给 m>1，后者对 m≥0 恒成立；同时还要避免两个解都大于 3，这不可能发生。所以在选项中满足的是 m=2。',
    difficulty: 'hard',
    points: 15,
    trainingStage: 'comprehensive',
    thinking: '这类北京风格参数题常把绝对值、范围和分类讨论揉在一起，关键是把两个解分开看。',
    steps: [
      {
        step: 1,
        title: '先写出绝对值方程解的形式',
        content: '当 m≥0 时，|x-2|=m 的解为 x=2+m 或 x=2-m。',
      },
      {
        step: 2,
        title: '逐个检查条件',
        content: '要求“恰有一个解满足 x>3”，所以先看 2+m>3，得到 m>1；另一个解 2-m 对 m≥0 时不可能大于 3。',
      },
      {
        step: 3,
        title: '回到选项判断',
        content: '在给定选项中，满足条件的是 m=2，所以选 B。',
        highlight: true,
      },
    ],
    keyPoints: ['绝对值方程', '分类讨论', '参数范围'],
    commonMistakes: ['把两个解混在一起讨论', '忘记先判断 m≥0'],
    district: '北京',
    examType: '中考风格改写',
  },
]
